# Generated by Django 4.0.2 on 2022-03-09 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('fighter_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('nickname', models.CharField(default='', max_length=256)),
                ('height', models.CharField(max_length=64)),
                ('weight_class', models.CharField(max_length=32)),
                ('association', models.CharField(default='', max_length=256)),
                ('country', models.CharField(default='', max_length=64)),
                ('upcoming_fight', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingFight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=64)),
                ('promotion', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('fighter', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='upcoming_fighter', to='upcoming_fights.fighter')),
                ('opponent', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='upcoming_opponent', to='upcoming_fights.fighter')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fighter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follow', to='upcoming_fights.fighter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follow', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
