# Generated by Django 4.0.2 on 2022-02-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('fighter_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('height', models.CharField(max_length=64)),
                ('weight_class', models.CharField(max_length=32)),
                ('record', models.CharField(max_length=32)),
                ('followers', models.IntegerField(default=0)),
            ],
        ),
    ]
