# Generated by Django 4.0.2 on 2022-03-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcoming_fights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='weight_class',
            field=models.CharField(max_length=128),
        ),
    ]
