# Generated by Django 4.0.2 on 2022-03-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcoming_fights', '0002_alter_fighter_weight_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingfight',
            name='date',
            field=models.DateField(),
        ),
    ]
