# Generated by Django 4.0.2 on 2022-02-22 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upcoming_fights', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fighter',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fighters_following',
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fighter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follow', to='upcoming_fights.fighter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follow', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
