# Generated by Django 4.0.2 on 2022-02-22 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upcoming_fights', '0003_remove_fighter_followers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingFight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=64)),
                ('promotion', models.CharField(max_length=128)),
                ('fighter', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='upcoming_fighter', to='upcoming_fights.fighter')),
                ('opponent', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='upcoming_opponent', to='upcoming_fights.fighter')),
            ],
        ),
    ]
