# Generated by Django 4.0.2 on 2022-03-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcoming_fights', '0003_alter_upcomingfight_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='followers',
            field=models.IntegerField(default=0),
        ),
    ]
