# Generated by Django 4.0.2 on 2022-02-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcoming_fights', '0005_fighter_upcoming_fight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fighter',
            name='record',
        ),
        migrations.AddField(
            model_name='fighter',
            name='association',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='fighter',
            name='nickname',
            field=models.CharField(default='', max_length=256),
        ),
    ]
