# Generated by Django 4.0.2 on 2022-02-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcoming_fights', '0006_remove_fighter_record_fighter_association_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='country',
            field=models.CharField(default='', max_length=64),
        ),
    ]
