# Generated by Django 4.0.2 on 2022-03-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcoming_fights', '0007_fighter_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingfight',
            name='location',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
